# application-dev.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/globoo?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
      schema-locations: classpath:db/init.sql
